import type_h

const
  EPERM* : cint32 = 1      # Operation not permitted
  ENOENT* : cint32 = 2     # No such file or directory
  ESRCH* : cint32 = 3      # No such process
  EINTR* : cint32 = 4      # Interrupted system call
  EIO* : cint32 = 5        # I/O error
  ENXIO* : cint32 = 6      # No such device or address
  E2BIG* : cint32 = 7      # Argument list too long
  ENOEXEC* : cint32 = 8    # Exec format error
  EBADF* : cint32 = 9      # Bad file number
  ECHILD* : cint32 = 10    # No child processes
  EAGAIN* : cint32 = 11    # Try again
  ENOMEM* : cint32 = 12    # Out of memory
  EACCES* : cint32 = 13    # Permission denied
  EFAULT* : cint32 = 14    # Bad address
  ENOTBLK* : cint32 = 15   # Block device required
  EBUSY* : cint32 = 16     # Device or resource busy
  EEXIST* : cint32 = 17    # File exists
  EXDEV* : cint32 = 18     # Cross-device link
  ENODEV* : cint32 = 19    # No such device
  ENOTDIR* : cint32 = 20   # Not a directory
  EISDIR* : cint32 = 21        # Is a directory
  EINVAL* : cint32 = 22        # Invalid argument
  ENFILE* : cint32 = 23        # File table overflow
  EMFILE* : cint32 = 24        # Too many open files
  ENOTTY* : cint32 = 25        # Not a typewriter
  ETXTBSY* : cint32 = 26       # Text file busy
  EFBIG* : cint32 = 27         # File too large
  ENOSPC* : cint32 = 28        # No space left on device
  ESPIPE* : cint32 = 29        # Illegal seek
  EROFS* : cint32 = 30         # Read-only file system
  EMLINK* : cint32 = 31        # Too many links
  EPIPE* : cint32 = 32         # Broken pipe
  EDOM* : cint32 = 33          # Math argument out of domain of func
  ERANGE* : cint32 = 34        # Math result not representable
  EDEADLK* : cint32 = 35       # Resource deadlock would occur
  ENAMETOOLONG* : cint32 = 36  # File name too long
  ENOLCK* : cint32 = 37        # No record locks available
  ENOSYS* : cint32 = 38        # Invalid system call number
  ENOTEMPTY* : cint32 = 39     # Directory not empty
  ELOOP* : cint32 = 40         # Too many symbolic links encountered
  EWOULDBLOCK* : cint32 = 11    # Operation would block (same as EAGAIN)
  ENOMSG* : cint32 = 42         # No message of desired type
  EIDRM* : cint32 = 43          # Identifier removed
  ECHRNG* : cint32 = 44         # Channel number out of range
  EL2NSYNC* : cint32 = 45       # Level 2 not synchronized
  EL3HLT* : cint32 = 46         # Level 3 halted
  EL3RST* : cint32 = 47         # Level 3 reset
  ELNRNG* : cint32 = 48         # Link number out of range
  EUNATCH* : cint32 = 49        # Protocol driver not attached
  ENOCSI* : cint32 = 50         # No CSI structure available
  EL2HLT* : cint32 = 51         # Level 2 halted
  EBADE* : cint32 = 52          # Invalid exchange
  EBADR* : cint32 = 53          # Invalid request descriptor
  EXFULL* : cint32 = 54         # Exchange full
  ENOANO* : cint32 = 55         # No anode
  EBADRQC* : cint32 = 56        # Invalid request code
  EBADSLT* : cint32 = 57        # Invalid slot
  EDEADLOCK* : cint32 = 35      # Resource deadlock would occur (alias of EDEADLK)
  EBFONT* : cint32 = 59         # Bad font file format
  ENOSTR* : cint32 = 60         # Device not a stream
  ENODATA* : cint32 = 61        # No data available
  ETIME* : cint32 = 62          # Timer expired
  ENOSR* : cint32 = 63          # Out of streams resources
  ENONET* : cint32 = 64         # Machine is not on the network
  ENOPKG* : cint32 = 65         # Package not installed
  EREMOTE* : cint32 = 66        # Object is remote
  ENOLINK* : cint32 = 67        # Link has been severed
  EADV* : cint32 = 68           # Advertise error
  ESRMNT* : cint32 = 69         # Srmount error
  ECOMM* : cint32 = 70          # Communication error on send
  EPROTO* : cint32 = 71         # Protocol error
  EMULTIHOP* : cint32 = 72      # Multihop attempted
  EDOTDOT* : cint32 = 73        # RFS specific error
  EBADMSG* : cint32 = 74        # Not a data message
  EOVERFLOW* : cint32 = 75      # Value too large for defined data type
  ENOTUNIQ* : cint32 = 76       # Name not unique on network
  EBADFD* : cint32 = 77         # File descriptor in bad state
  EREMCHG* : cint32 = 78        # Remote address changed
  ELIBACC* : cint32 = 79        # Can not access a needed shared library
  ELIBBAD* : cint32 = 80        # Accessing a corrupted shared library
  ELIBSCN* : cint32 = 81        # .lib section in a.out corrupted
  ELIBMAX* : cint32 = 82        # Attempting to link in too many shared libraries
  ELIBEXEC* : cint32 = 83       # Cannot exec a shared library directly
  EILSEQ* : cint32 = 84         # Illegal byte sequence
  ERESTART* : cint32 = 85       # Interrupted system call should be restarted
  ESTRPIPE* : cint32 = 86       # Streams pipe error
  EUSERS* : cint32 = 87         # Too many users
  ENOTSOCK* : cint32 = 88       # Socket operation on non-socket
  EDESTADDRREQ* : cint32 = 89   # Destination address required
  EMSGSIZE* : cint32 = 90       # Message too long
  EPROTOTYPE* : cint32 = 91     # Protocol wrong type for socket
  ENOPROTOOPT* : cint32 = 92    # Protocol not available
  EPROTONOSUPPORT* : cint32 = 93 # Protocol not supported
  ESOCKTNOSUPPORT* : cint32 = 94 # Socket type not supported
  EOPNOTSUPP* : cint32 = 95     # Operation not supported on transport endpoint
  EPFNOSUPPORT* : cint32 = 96   # Protocol family not supported
  EAFNOSUPPORT* : cint32 = 97   # Address family not supported by protocol
  EADDRINUSE* : cint32 = 98     # Address already in use
  EADDRNOTAVAIL* : cint32 = 99  # Cannot assign requested address
  ENETDOWN* : cint32 = 100      # Network is down
  ENETUNREACH* : cint32 = 101       # Network is unreachable
  ENETRESET* : cint32 = 102         # Network dropped connection because of reset
  ECONNABORTED* : cint32 = 103      # Software caused connection abort
  ECONNRESET* : cint32 = 104        # Connection reset by peer
  ENOBUFS* : cint32 = 105           # No buffer space available
  EISCONN* : cint32 = 106           # Transport endpoint is already connected
  ENOTCONN* : cint32 = 107          # Transport endpoint is not connected
  ESHUTDOWN* : cint32 = 108         # Cannot send after transport endpoint shutdown
  ETOOMANYREFS* : cint32 = 109      # Too many references: cannot splice
  ETIMEDOUT* : cint32 = 110         # Connection timed out
  ECONNREFUSED* : cint32 = 111      # Connection refused
  EHOSTDOWN* : cint32 = 112         # Host is down
  EHOSTUNREACH* : cint32 = 113      # No route to host
  EALREADY* : cint32 = 114          # Operation already in progress
  EINPROGRESS* : cint32 = 115       # Operation now in progress
  ESTALE* : cint32 = 116            # Stale file handle
  EUCLEAN* : cint32 = 117           # Structure needs cleaning
  ENOTNAM* : cint32 = 118           # Not a XENIX named type file
  ENAVAIL* : cint32 = 119           # No XENIX semaphores available
  EISNAM* : cint32 = 120            # Is a named type file
  EREMOTEIO* : cint32 = 121         # Remote I/O error
  EDQUOT* : cint32 = 122            # Quota exceeded
  ENOMEDIUM* : cint32 = 123         # No medium found
  EMEDIUMTYPE* : cint32 = 124       # Wrong medium type
  ECANCELED* : cint32 = 125         # Operation Canceled
  ENOKEY* : cint32 = 126            # Required key not available
  EKEYEXPIRED* : cint32 = 127       # Key has expired
  EKEYREVOKED* : cint32 = 128       # Key has been revoked
  EKEYREJECTED* : cint32 = 129      # Key was rejected by service
  EOWNERDEAD* : cint32 = 130        # Owner died
  ENOTRECOVERABLE* : cint32 = 131   # State not recoverable
  ERFKILL* : cint32 = 132           # Operation not possible due to RF-kill
  EHWPOISON* : cint32 = 133         # Memory page has hardware error